EBR-76: TVB logo to readme files
the-virtual-brain/tvb-ext-xircuits pull request #55
Opened 2024-10-31 10:26 UTC by AdrianValentinCiu

2024-10-31 10:38 UTC, liadomide requested changes
This would need a rebase against `mergeFromXircuitsRepo` branch
I would see the logo added just in the `README.md`

2024-11-01 14:37 UTC, liadomide approved these changes

2024-11-01 14:43 UTC, romina1601 approved these changes

2024-11-01 14:52 UTC, 915-Misan-Teodora approved these changes

2024-11-01 15:04 UTC, merged