EBR-115. Create 2 options for installing the library
the-virtual-brain/tvb-ext-xircuits pull request #56
Opened 2024-11-04 12:15 UTC by romina1601

We need to separate frontend dependencies from backend dependencies

2024-11-04 12:24 UTC, liadomide approved these changes
I could not test this., but by reading the code change it looks fine to me.

2024-11-04 12:24 UTC, liadomide requested changes
But we should also change the build actions s to install full, not light

2024-11-04 20:31 UTC, liadomide approved these changes

2024-11-05 08:14 UTC, 915-Misan-Teodora approved these changes

2024-11-05 08:15 UTC, merged